DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
  ID int(11) NOT NULL AUTO_INCREMENT,
  AUTHOR varchar(255) DEFAULT NULL,
  CATEGORY varchar(255) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  PAGES int(11) DEFAULT NULL,
  PRICE int(11) DEFAULT NULL,
  PUBLICATION varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID)
);




